Header header
float64 surge_e # surge error
float64 sway_e # sway error
float64 heave_e # heave error
float64 roll_e # roll error
float64 pitch_e # pitch error
float64 yaw_e # yaw error
float64 surge_rate_e # surge rate error
float64 sway_rate_e # sway rate error
float64 heave_rate_e # heave rate error
float64 roll_rate_e # roll rate error
float64 pitch_rate_e # pitch rate error
float64 yaw_rate_e # yaw rate error
